# Generated by Django 4.1.13 on 2024-01-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_student_email_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolled',
            unique_together={('subject', 'student', 'period')},
        ),
    ]
